//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wechat_Notifier.VballMangerWebservice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VballMangerWebservice.VballWebServiceSoap")]
    public interface VballWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name WechatMessagesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WechatMessages", ReplyAction="*")]
        Wechat_Notifier.VballMangerWebservice.WechatMessagesResponse WechatMessages(Wechat_Notifier.VballMangerWebservice.WechatMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WechatMessages", ReplyAction="*")]
        System.Threading.Tasks.Task<Wechat_Notifier.VballMangerWebservice.WechatMessagesResponse> WechatMessagesAsync(Wechat_Notifier.VballMangerWebservice.WechatMessagesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WechatMessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WechatMessages", Namespace="http://tempuri.org/", Order=0)]
        public Wechat_Notifier.VballMangerWebservice.WechatMessagesRequestBody Body;
        
        public WechatMessagesRequest() {
        }
        
        public WechatMessagesRequest(Wechat_Notifier.VballMangerWebservice.WechatMessagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class WechatMessagesRequestBody {
        
        public WechatMessagesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WechatMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WechatMessagesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Wechat_Notifier.VballMangerWebservice.WechatMessagesResponseBody Body;
        
        public WechatMessagesResponse() {
        }
        
        public WechatMessagesResponse(Wechat_Notifier.VballMangerWebservice.WechatMessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WechatMessagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Wechat_Notifier.VballMangerWebservice.ArrayOfString WechatMessagesResult;
        
        public WechatMessagesResponseBody() {
        }
        
        public WechatMessagesResponseBody(Wechat_Notifier.VballMangerWebservice.ArrayOfString WechatMessagesResult) {
            this.WechatMessagesResult = WechatMessagesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VballWebServiceSoapChannel : Wechat_Notifier.VballMangerWebservice.VballWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VballWebServiceSoapClient : System.ServiceModel.ClientBase<Wechat_Notifier.VballMangerWebservice.VballWebServiceSoap>, Wechat_Notifier.VballMangerWebservice.VballWebServiceSoap {
        
        public VballWebServiceSoapClient() {
        }
        
        public VballWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VballWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VballWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VballWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Wechat_Notifier.VballMangerWebservice.WechatMessagesResponse Wechat_Notifier.VballMangerWebservice.VballWebServiceSoap.WechatMessages(Wechat_Notifier.VballMangerWebservice.WechatMessagesRequest request) {
            return base.Channel.WechatMessages(request);
        }
        
        public Wechat_Notifier.VballMangerWebservice.ArrayOfString WechatMessages() {
            Wechat_Notifier.VballMangerWebservice.WechatMessagesRequest inValue = new Wechat_Notifier.VballMangerWebservice.WechatMessagesRequest();
            inValue.Body = new Wechat_Notifier.VballMangerWebservice.WechatMessagesRequestBody();
            Wechat_Notifier.VballMangerWebservice.WechatMessagesResponse retVal = ((Wechat_Notifier.VballMangerWebservice.VballWebServiceSoap)(this)).WechatMessages(inValue);
            return retVal.Body.WechatMessagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wechat_Notifier.VballMangerWebservice.WechatMessagesResponse> Wechat_Notifier.VballMangerWebservice.VballWebServiceSoap.WechatMessagesAsync(Wechat_Notifier.VballMangerWebservice.WechatMessagesRequest request) {
            return base.Channel.WechatMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wechat_Notifier.VballMangerWebservice.WechatMessagesResponse> WechatMessagesAsync() {
            Wechat_Notifier.VballMangerWebservice.WechatMessagesRequest inValue = new Wechat_Notifier.VballMangerWebservice.WechatMessagesRequest();
            inValue.Body = new Wechat_Notifier.VballMangerWebservice.WechatMessagesRequestBody();
            return ((Wechat_Notifier.VballMangerWebservice.VballWebServiceSoap)(this)).WechatMessagesAsync(inValue);
        }
    }
}
