//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wechat_Notifier.ActivityWebservice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WechatMessage", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class WechatMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WechatNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string WechatName {
            get {
                return this.WechatNameField;
            }
            set {
                if ((object.ReferenceEquals(this.WechatNameField, value) != true)) {
                    this.WechatNameField = value;
                    this.RaisePropertyChanged("WechatName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string At {
            get {
                return this.AtField;
            }
            set {
                if ((object.ReferenceEquals(this.AtField, value) != true)) {
                    this.AtField = value;
                    this.RaisePropertyChanged("At");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ActivityWebservice.ActivityWebServiceSoap")]
    public interface ActivityWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name WechatMessagesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WechatMessages", ReplyAction="*")]
        Wechat_Notifier.ActivityWebservice.WechatMessagesResponse WechatMessages(Wechat_Notifier.ActivityWebservice.WechatMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WechatMessages", ReplyAction="*")]
        System.Threading.Tasks.Task<Wechat_Notifier.ActivityWebservice.WechatMessagesResponse> WechatMessagesAsync(Wechat_Notifier.ActivityWebservice.WechatMessagesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WechatMessagesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WechatMessages", Namespace="http://tempuri.org/", Order=0)]
        public Wechat_Notifier.ActivityWebservice.WechatMessagesRequestBody Body;
        
        public WechatMessagesRequest() {
        }
        
        public WechatMessagesRequest(Wechat_Notifier.ActivityWebservice.WechatMessagesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class WechatMessagesRequestBody {
        
        public WechatMessagesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WechatMessagesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WechatMessagesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Wechat_Notifier.ActivityWebservice.WechatMessagesResponseBody Body;
        
        public WechatMessagesResponse() {
        }
        
        public WechatMessagesResponse(Wechat_Notifier.ActivityWebservice.WechatMessagesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WechatMessagesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Wechat_Notifier.ActivityWebservice.WechatMessage[] WechatMessagesResult;
        
        public WechatMessagesResponseBody() {
        }
        
        public WechatMessagesResponseBody(Wechat_Notifier.ActivityWebservice.WechatMessage[] WechatMessagesResult) {
            this.WechatMessagesResult = WechatMessagesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ActivityWebServiceSoapChannel : Wechat_Notifier.ActivityWebservice.ActivityWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ActivityWebServiceSoapClient : System.ServiceModel.ClientBase<Wechat_Notifier.ActivityWebservice.ActivityWebServiceSoap>, Wechat_Notifier.ActivityWebservice.ActivityWebServiceSoap {
        
        public ActivityWebServiceSoapClient() {
        }
        
        public ActivityWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ActivityWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActivityWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActivityWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Wechat_Notifier.ActivityWebservice.WechatMessagesResponse Wechat_Notifier.ActivityWebservice.ActivityWebServiceSoap.WechatMessages(Wechat_Notifier.ActivityWebservice.WechatMessagesRequest request) {
            return base.Channel.WechatMessages(request);
        }
        
        public Wechat_Notifier.ActivityWebservice.WechatMessage[] WechatMessages() {
            Wechat_Notifier.ActivityWebservice.WechatMessagesRequest inValue = new Wechat_Notifier.ActivityWebservice.WechatMessagesRequest();
            inValue.Body = new Wechat_Notifier.ActivityWebservice.WechatMessagesRequestBody();
            Wechat_Notifier.ActivityWebservice.WechatMessagesResponse retVal = ((Wechat_Notifier.ActivityWebservice.ActivityWebServiceSoap)(this)).WechatMessages(inValue);
            return retVal.Body.WechatMessagesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Wechat_Notifier.ActivityWebservice.WechatMessagesResponse> Wechat_Notifier.ActivityWebservice.ActivityWebServiceSoap.WechatMessagesAsync(Wechat_Notifier.ActivityWebservice.WechatMessagesRequest request) {
            return base.Channel.WechatMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Wechat_Notifier.ActivityWebservice.WechatMessagesResponse> WechatMessagesAsync() {
            Wechat_Notifier.ActivityWebservice.WechatMessagesRequest inValue = new Wechat_Notifier.ActivityWebservice.WechatMessagesRequest();
            inValue.Body = new Wechat_Notifier.ActivityWebservice.WechatMessagesRequestBody();
            return ((Wechat_Notifier.ActivityWebservice.ActivityWebServiceSoap)(this)).WechatMessagesAsync(inValue);
        }
    }
}
