//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VballManager {
	
	
	public partial class SiteMaster {
		
		protected System.Web.UI.WebControls.ContentPlaceHolder HeadContent;
		
		protected System.Web.UI.WebControls.Label TitleLabel;
		
		protected System.Web.UI.WebControls.TextBox PasscodeTb;
		
		protected System.Web.UI.WebControls.LoginView HeadLoginView;
		
		protected System.Web.UI.WebControls.Menu NavigationMenu;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder MainContent;
	}
}
